package thriving.softwood.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import thriving.softwood.pojo.entity.Cinema;

@Mapper
public interface CinemaMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cinema
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cinema
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int insert(Cinema row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cinema
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    Cinema selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cinema
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    List<Cinema> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cinema
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int updateByPrimaryKey(Cinema row);
}