package thriving.softwood.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import thriving.softwood.pojo.dto.CommentDTO;
import thriving.softwood.pojo.entity.Comment;

@Mapper
public interface CommentMapper {

    // 手动方法 begin
    List<Comment> list(CommentDTO dto);

    // 手动方法 end

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int insert(Comment row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    Comment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int updateByPrimaryKey(Comment row);
}