package thriving.softwood.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import thriving.softwood.pojo.dto.MovieQryDTO;
import thriving.softwood.pojo.entity.Movie;

/**
 * @author ThrivingSoftwood
 */
@Mapper
public interface MovieMapper {

    // 手写方法 begin

    List<Movie> list(MovieQryDTO dto);

    // 手写方法 end

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table movie
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table movie
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int insert(Movie row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table movie
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    Movie selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table movie
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    List<Movie> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table movie
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int updateByPrimaryKey(Movie row);
}