package thriving.softwood.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import thriving.softwood.pojo.entity.Order;

@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table order
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table order
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int insert(Order row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table order
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    Order selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table order
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table order
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int updateByPrimaryKey(Order row);
}