package thriving.softwood.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import thriving.softwood.pojo.entity.Schedule;

@Mapper
public interface ScheduleMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int insert(Schedule row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    Schedule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    List<Schedule> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int updateByPrimaryKey(Schedule row);
}