package thriving.softwood.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import thriving.softwood.pojo.dto.UserDTO;
import thriving.softwood.pojo.entity.User;

@Mapper
public interface UserMapper {

    // 手动方法 begin
    List<User> list(UserDTO dto);

    Integer add(UserDTO dto);

    // 手动方法 end

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    int updateByPrimaryKey(User row);
}