package thriving.softwood.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import thriving.softwood.pojo.entity.Hall;

@Mapper
public interface HallMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hall
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hall
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    int insert(Hall row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hall
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    Hall selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hall
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    List<Hall> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hall
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    int updateByPrimaryKey(Hall row);
}