package thriving.softwood.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import thriving.softwood.pojo.entity.Movie;

@Mapper
public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table movie
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table movie
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    int insert(Movie row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table movie
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    Movie selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table movie
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    List<Movie> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table movie
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    int updateByPrimaryKey(Movie row);
}