package thriving.softwood.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import thriving.softwood.pojo.entity.User;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    int updateByPrimaryKey(User row);
}