package thriving.softwood.pojo.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Cinema implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column cinema.id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column cinema.cinema_name
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String cinemaName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cinema.cinema_address
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String cinemaAddress;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column cinema.create_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column cinema.update_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table cinema
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private static final long serialVersionUID = 1L;
}