package thriving.softwood.pojo.entity;

import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Cinema implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema.id
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema.cinema_name
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String cinemaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema.cinema_address
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String cinemaAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cinema
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private static final long serialVersionUID = 1L;
}