package thriving.softwood.pojo.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Comment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column comment.id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * comment.comment_content
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String commentContent;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column comment.movie_id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long movieId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column comment.comment_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime commentTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column comment.create_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column comment.update_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table comment
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private static final long serialVersionUID = 1L;
}