package thriving.softwood.pojo.entity;

import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Hall implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.id
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.hall_name
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String hallName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.hall_capacity
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Integer hallCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.cinema_id
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long cinemaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hall
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private static final long serialVersionUID = 1L;
}