package thriving.softwood.pojo.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Hall implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column hall.id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column hall.hall_name
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String hallName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column hall.hall_capacity
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Integer hallCapacity;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column hall.cinema_id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long cinemaId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column hall.create_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column hall.update_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table hall
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private static final long serialVersionUID = 1L;
}