package thriving.softwood.pojo.entity;

import java.io.Serializable;
import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Movie implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.id
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_cn_name
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String movieCnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_fg_name
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String movieFgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_actor
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String movieActor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_director
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String movieDirector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_detail
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String movieDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_duration
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String movieDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_type
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String movieType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_score
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Float movieScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_boxOffice
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Float movieBoxoffice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_commentCount
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long movieCommentcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_releaseDate
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private LocalDate movieReleasedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_country
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String movieCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_picture
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String moviePicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_state
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Integer movieState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table movie
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private static final long serialVersionUID = 1L;
}