package thriving.softwood.pojo.entity;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author ThrivingSoftwood
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Movie implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_cn_name
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String movieCnName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_fg_name
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String movieFgName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_actor
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String movieActor;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_director
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String movieDirector;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_detail
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String movieDetail;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_duration
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String movieDuration;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_type
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String movieType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_score
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    public static final String COL_MOVIE_SCORE = "movie_score";
    private Float movieScore;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * movie.movie_box_office
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    public static final String COL_BOX_OFFICE = "movie_box_office";
    private Float movieBoxOffice;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * movie.movie_comment_count
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    public static final String COL_COMMENT_COUNT = "movie_comment_count";
    private Long movieCommentCount;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * movie.movie_release_date
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    public static final String COL_RELEASE_DATE = "movie_release_date";
    private LocalDate movieReleaseDate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_country
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String movieCountry;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_picture
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String moviePicture;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_state
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Integer movieState;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.create_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column movie.update_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table movie
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private static final long serialVersionUID = 1L;
}