package thriving.softwood.pojo.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author ThrivingSoftwood
 */
@Data
@NoArgsConstructor
public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column order.id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column order.user_id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column order.schedule_id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long scheduleId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column order.order_position
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String orderPosition;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column order.order_state
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Integer orderState;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column order.order_price
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Integer orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column order.order_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime orderTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column order.create_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    @JsonIgnore
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column order.update_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    @JsonIgnore
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table order
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    @JsonIgnore
    private static final long serialVersionUID = 1L;
}