package thriving.softwood.pojo.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.schedule_id
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long scheduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_position
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String orderPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_state
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Integer orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_price
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Integer orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_time
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private LocalDateTime orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private static final long serialVersionUID = 1L;
}