package thriving.softwood.pojo.entity;

import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Schedule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.id
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.hall_id
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long hallId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.movie_id
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Long movieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.schedule_startTime
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private String scheduleStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.schedule_price
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Integer schedulePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.schedule_remain
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Integer scheduleRemain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.schedule_state
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private Integer scheduleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated Wed Jan 14 19:06:17 CST 2026
     */
    private static final long serialVersionUID = 1L;
}