package thriving.softwood.pojo.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author ThrivingSoftwood
 */
@Data
@NoArgsConstructor
public class Schedule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.hall_id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long hallId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.movie_id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long movieId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * schedule.schedule_start_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String scheduleStartTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * schedule.schedule_price
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Integer schedulePrice;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * schedule.schedule_remain
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Integer scheduleRemain;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * schedule.schedule_state
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Integer scheduleState;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.create_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    @JsonIgnore
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.update_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    @JsonIgnore
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schedule
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    @JsonIgnore
    private static final long serialVersionUID = 1L;
}