package thriving.softwood.pojo.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_name
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_pwd
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_email
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_role
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private Integer userRole;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_headImg
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private String userHeadimg;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_time
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table user
     *
     * @mbg.generated Thu Jan 15 18:52:49 CST 2026
     */
    private static final long serialVersionUID = 1L;
}